---
image:
  repository: apache/kudu
  version: 1.10.0
  imagePullPolicy: IfNotPresent

master:
  replicas: 3
  storageSize: 100Gi
  storageClass: gp2
  resources: {}
    # limits:
    #  cpu: 1000m
    #  memory: 1Gi
    # requests:
    #  cpu: 100m
    #  memory: 128Mi
  nodeSelector: {}
  tolerations: []
  affinity: {}
tserver:
  replicas: 3
  storageSize: 100Gi
  storageClass: gp2
  resources: {}
    # limits:
    #  cpu: 1000m
    #  memory: 4Gi
    # requests:
    #  cpu: 100m
    #  memory: 2Gi
  nodeSelector: {}
  tolerations: []
  affinity: {}
