---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: default-ingress
  namespace: {{ .Values.name}}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
{{- range $node := .Values.nodes }}
  - host: {{ $node.name_namespace }}-{{ $node.name }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $node.name }}
          servicePort: {{ $node.ui_port }}
{{- end }}
