apiVersion: v1
kind: Service
metadata:
  name: {{ include "kudu.fullname" . }}-tserver-headless
  labels:
    app.kubernetes.io/name: {{ include "kudu.name" . }}
    helm.sh/chart: {{ include "kudu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 8050
      targetPort: ui
      name: ui
    - port: 7050
      targetPort: rpc
      name: rpc
  selector:
    app.kubernetes.io/name: {{ include "kudu.name" . }}
    helm.sh/chart: {{ include "kudu.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
